# Generated by Django 5.2 on 2025-05-23 09:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('news', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ticker', models.CharField(max_length=10)),
                ('title', models.CharField(max_length=300)),
                ('content', models.TextField()),
                ('pub_date', models.DateTimeField()),
            ],
            options={
                'db_table': 'sa_article',
                'ordering': ['-pub_date'],
            },
        ),
        migrations.CreateModel(
            name='ArticleAnalysis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sentiment_score', models.FloatField()),
                ('sentiment_label', models.CharField(max_length=10)),
                ('combined_score', models.FloatField()),
                ('relevance', models.CharField(max_length=6)),
                ('keyword_score', models.FloatField()),
                ('ticker_count', models.IntegerField()),
                ('figures_count', models.IntegerField()),
                ('article', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='analysis', to='sentiment_analysis.article')),
            ],
        ),
        migrations.CreateModel(
            name='NewsAnalysis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sentiment_score', models.FloatField()),
                ('sentiment_label', models.CharField(max_length=10)),
                ('combined_score', models.FloatField()),
                ('relevance', models.CharField(max_length=6)),
                ('keyword_score', models.FloatField()),
                ('ticker_count', models.IntegerField()),
                ('figures_count', models.IntegerField()),
                ('news', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='sentiment_analysis', to='news.new')),
            ],
        ),
    ]
