# Generated by Django 5.2 on 2025-04-07 17:44

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='New',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('publisher', models.CharField(max_length=255)),
                ('link', models.URLField()),
                ('provider_publish_time', models.BigIntegerField()),
                ('news_type', models.CharField(max_length=50)),
                ('thumbnail', models.JSONField(blank=True, null=True)),
                ('related_tickers', models.JSONField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Quote',
            fields=[
                ('exchange', models.CharField(max_length=50)),
                ('shortname', models.CharField(max_length=255)),
                ('quote_type', models.CharField(max_length=50)),
                ('symbol', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('index', models.CharField(max_length=50)),
                ('score', models.FloatField()),
                ('type_disp', models.CharField(max_length=50)),
                ('longname', models.CharField(max_length=255)),
                ('exch_disp', models.CharField(max_length=50)),
                ('sector', models.CharField(max_length=100)),
                ('sector_disp', models.CharField(max_length=100)),
                ('industry', models.CharField(max_length=255)),
                ('industry_disp', models.CharField(max_length=255)),
                ('is_yahoo_finance', models.BooleanField(default=False)),
                ('prev_name', models.CharField(blank=True, max_length=255, null=True)),
                ('name_change_date', models.DateField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Research',
            fields=[
                ('research_id', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('report_headline', models.CharField(max_length=255)),
                ('author', models.CharField(max_length=255)),
                ('report_date', models.BigIntegerField()),
                ('provider', models.CharField(max_length=100)),
            ],
        ),
    ]
