name: Deploy Sphinx docs to GitHub Pages

env:
  DEBUG: False
  DJANGO_SECRET_KEY: ${{ secrets.DJANGO_SECRET_KEY }}
  DBUSER: ${{ secrets.DBUSER }}
  DBPASS: ${{ secrets.DBPASS }}
  DBNAME: ${{ secrets.DBNAME }}
  DBHOST: ${{ secrets.DBHOST }}
  CELERY_RESULT_BACKEND: ${{ secrets.CELERY_RESULT_BACKEND }}
  CELERY_BROKER_URL: ${{ secrets.CELERY_BROKER_URL }}
  WEBSITE_HOSTNAME: ${{ vars.WEBSITE_HOSTNAME }}
  FRONTEND_URL: ${{ vars.FRONTEND_URL }}
  VITE_API_BASE_URL_PROD: ${{ secrets.VITE_API_BASE_URL_PROD }}

on:
  push:
    branches:
      - news-trader-django-azure-web-app
    # branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.13.3"

      - name: Install Sphinx
        run: |
          pip install -r requirements.txt
          pip install sphinx sphinx-autodoc-typehints sphinx_rtd_theme

      - name: Build docs
        run: |
          export DJANGO_SETTINGS_MODULE=news_trader.settings
          cd docs
          make html

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: docs/build/html
