name: Deploy Sphinx docs to GitHub Pages

on:
  push:
    branches:
      - news-trader-django-azure-web-app
    # branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.13.3"

      - name: Install Sphinx
        run: |
          pip install -r requirements.txt
          pip install sphinx sphinx-autodoc-typehints sphinx_rtd_theme

      - name: Build docs
        run: |
          export DJANGO_SETTINGS_MODULE=news_trader.settings
          cd docs
          make html

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: docs/build/html
